### ISSUE TITLE
re: plantuml.jar

### ISSUE THREAD

**Issue by TopView** [lodahl/Libo_PlantUML#10]
Aloha,

 Libo_PlantUML/Libo_PlantUML/pkg-desc/pkg-description.txt  says, "plantuml.jar must be copied to HOME/plantuml/ where HOME refers to your personal home directory. Om Windows that is in \Documents\plantuml".

But current release at https://extensions.libreoffice.org/extensions/libo_plantuml still says, 

"Current Release
Libo_PlantUML - 1.1.0
...
Most important feature is that plantuml.jar now is embedded in the extension."

So does this line about "plantuml.jar must be copied to HOME..." need to now be removed??

**Comment by lodahl** [comment]
Fixed in 1.2.0
