### ISSUE TITLE
How to quickly get started...

### ISSUE THREAD

**Issue by TopView** [lodahl/Libo_PlantUML#11]
Hi again,  

Pretty cool, but on, [https://extensions.libreoffice.org/extensions/libo_plantuml](https://extensions.libreoffice.org/extensions/libo_plantuml), it left me kind of confused how to actually use this extension.  

I think it might be good on that page to say, something like the following:

==================================================================

To quickly get started with an example do these four steps:

1) Install this extension,
2) Open a new LO Writer document,
3) Insert the following text into your document:

@startuml
Object <|-- ArrayList

Object : equals()
ArrayList : Object[] elementData
ArrayList : size()

4) Notice the two new black and purple icons that have been added to the left side of your menu bar.  Click the left most one, that looks like a frame with an asterix at the lower left, to generate the diagram.

==================================================================

**Comment by TopView** [comment]
Awsome!  Thanks Leif.

**Comment by lodahl** [comment]
A getting started manual is now available on Github ( https://github.com/lodahl/Libo_PlantUML ) and on the extension website( https://extensions.libreoffice.org/extensions/libo_plantuml/ )

**Comment by lodahl** [comment]
Done.
